config/routes.rb
Rails.application.routes.draw do
  root 'public#home'
  
  get 'access/index'

  get 'access/login'

  get 'public/about_us'

  get 'public/contact_us'

  get 'public/home'

  get 'public/events'

  get 'public', :to => 'public#home'

  resources :admin_users

  resources :events

  resources :members

  match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/event.rb
class Event < ActiveRecord::Base
	acts_as_list

	#associations
	has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50#" }, default_url: "/images/:style/missing.png"
	has_attached_file :image2, styles: { medium: "300x300>", thumb: "50x50#" }, default_url: "/images/:style/missing.png"
	has_attached_file :image3, styles: { medium: "300x300>", thumb: "50x50#" }, default_url: "/images/:style/missing.png"
	has_attached_file :image4, styles: { medium: "300x300>", thumb: "50x50#" }, default_url: "/images/:style/missing.png"

	scope :sorted, lambda{order("events.time DESC")}

	#validation
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates_attachment_content_type :image2, content_type: /\Aimage\/.*\Z/
	validates_attachment_content_type :image3, content_type: /\Aimage\/.*\Z/
	validates_attachment_content_type :image4, content_type: /\Aimage\/.*\Z/
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :confirm_login
  # GET /events
  # GET /events.json


  def index
    @events = Event.all.sorted
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    if Event.all.blank?
      @event = Event.new
    else
    last = Event.all.last!.position + 1
    @event = Event.new(:position => last )
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :position, :time, :details, :place, :line2, :image, :image2, :image3, :image4)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

    <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:position]) %>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :time, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:time]) %>
  </div>
  <div class="control-group">
    <%= f.label :details, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :details, :rows => 5 , :class => 'form-control' %>
    </div>
    <%= error_span(@event[:details]) %>
  </div>
  <div class="control-group">
    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :place, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:place]) %>
  </div>
  <div class="control-group">
    <%= f.label :line2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :line2, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:line2]) %>
  </div>
  <div class="control-group">
    <%= f.label :image_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image]) %>
  </div>

  <div class="control-group">
    <%= f.label :image2_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image2_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image2_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :image2, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image2, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image2]) %>
  </div>
  <div class="control-group">
    <%= f.label :image3_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image3_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image3_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :image3, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image3, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image3]) %>
  </div>
  <div class="control-group">
    <%= f.label :image4_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image4_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image4_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :image4, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image4, :class => 'form-control' %>
    </div>
    <%= error_span(@event[:image4]) %>
  </div>

<br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            events_path, :class => 'btn btn-default' %>

<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.position, event_path(event) %></td>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= time_tag event.time %></td>
        <td><%= event.place %></td>
        <td><%= time_ago_in_words(event.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/public.html.erb
<h1>Public</h1>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => @event.name.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @event.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @event.time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @event.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @event.place %></dd>
  <dt><strong><%= model_class.human_attribute_name(:line2) %>:</strong></dt>
  <dd><%= @event.line2 %></dd>
  <dt><strong><%= model_class.human_attribute_name("Images") %>:</strong></dt>
  <dd>
  <%= image_tag @event.image.url(:medium) %><br>
  <% unless @event.image2.blank? %><%= image_tag @event.image2.url(:medium) %><% end%><br>
  <% unless @event.image3.blank? %><%= image_tag @event.image3.url(:medium) %><% end%><br>
  <% unless @event.image4.blank? %><%= image_tag @event.image4.url(:medium) %><% end%>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>