config/routes.rb
Rails.application.routes.draw do
  root 'public#home'
  
  get 'access/index'

  get 'access/login'

  get 'public/about_us'

  get 'public/contact_us'

  get 'public/home'

  get 'public/events'

  get 'public', :to => 'public#home'

  resources :admin_users

  resources :events

  resources :members

  match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	#associations
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50#" }, default_url: "/images/:style/missing.png"
	has_secure_password
	scope :sorted, lambda{ order("admin_users.id ASC") }
	#validation
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  before_action :confirm_login
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin_users
  # GET /admin_users.json
  def index
    @admin_users = AdminUser.all.sorted
  end

  # GET /admin_users/1
  # GET /admin_users/1.json
  def show
  end

  # GET /admin_users/new
  def new
    @admin_user = AdminUser.new
  end

  # GET /admin_users/1/edit
  def edit
  end

  # POST /admin_users
  # POST /admin_users.json
  def create
    @admin_user = AdminUser.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_users/1
  # PATCH/PUT /admin_users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'Admin user was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'Admin user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = AdminUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:username, :password, :adminstrator, :email, :avatar)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= form_for @admin_user, :html => { :class => "form-horizontal admin_user" } do |f| %>

    <% if @admin_user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @admin_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:username]) %>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:password_digest]) %>
  </div>
  <div class="control-group">
    <%= f.label :adminstrator, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :adminstrator, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:adminstrator]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :avatar_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:avatar_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:avatar]) %>
  </div>


<br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            admin_users_path, :class => 'btn btn-default' %>

<% end %>

app/views/admin_users/edit.html.erb
<%- model_class = AdminUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin_users/index.html.erb
<%- model_class = AdminUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name("Avatar") %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:adminstrator) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= link_to admin_user.id, admin_user_path(admin_user) %></td>
        <td><%= image_tag admin_user.avatar.url(:thumb) %></td>
        <td><%= link_to admin_user.username, admin_user_path(admin_user) %></td>
        <td><%= admin_user.adminstrator %></td>
        <td><%= admin_user.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_user_path(admin_user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_user_path(admin_user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_user_path,
            :class => 'btn btn-primary' %>

app/views/admin_users/new.html.erb
<%- model_class = AdminUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin_users/show.html.erb
<%- model_class = AdminUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @admin_user.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @admin_user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adminstrator) %>:</strong></dt>
  <dd><%= @admin_user.adminstrator %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @admin_user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @admin_user.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @admin_user.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @admin_user.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @admin_user.avatar_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_user_path(@admin_user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_user_path(@admin_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>