config/routes.rb
Rails.application.routes.draw do
  root 'public#home'
  
  get 'access/index'

  get 'access/login'

  get 'public/about_us'

  get 'public/contact_us'

  get 'public/home'

  get 'public/events'

  get 'public', :to => 'public#home'

  resources :admin_users

  resources :events

  resources :members

  match ':controller(/:action(/:id))', :via => [:get,:post]

end

app/models/member.rb
class Member < ActiveRecord::Base

	#associations
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	has_attached_file :avatar2, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	acts_as_list

	scope :sorted, lambda{order("members.position ASC")}

	#validation
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validates_attachment_content_type :avatar2, content_type: /\Aimage\/.*\Z/

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :confirm_login

  # GET /members
  # GET /members.json


  def index
    @members = Member.all.sorted
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :position, :job_title, :line2, :description, :avatar, :avatar2)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

    <% if @member.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:position]) %>
  </div>
  <div class="control-group">
    <%= f.label :job_title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :job_title, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:job_title]) %>
  </div>
  <div class="control-group">
    <%= f.label :line2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :line2, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:line2]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows => 5 , :class => 'form-control' %>
    </div>
    <%= error_span(@member[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :avatar_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:avatar_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:avatar]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar2_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :avatar2_file_name, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:avatar2_file_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar2, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar2, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:avatar2]) %>
  </div>

<br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            members_path, :class => 'btn btn-default' %>

<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:job_title) %></th>
      <th><%= model_class.human_attribute_name(:line2) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.position, member_path(member) %></td>
        <td><%= member.name %></td>
        <td><%= member.job_title %></td>
        <td><%= member.line2 %></td>
        <td><%= time_ago_in_words(member.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/public.html.erb
<h1>Public</h1>

app/views/members/show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @member.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @member.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_title) %>:</strong></dt>
  <dd><%= @member.job_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:line2) %>:</strong></dt>
  <dd><%= @member.line2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @member.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @member.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @member.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @member.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @member.avatar_updated_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar2_file_name) %>:</strong></dt>
  <dd><%= @member.avatar2_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar2_content_type) %>:</strong></dt>
  <dd><%= @member.avatar2_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar2_file_size) %>:</strong></dt>
  <dd><%= @member.avatar2_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar2_updated_at) %>:</strong></dt>
  <dd><%= @member.avatar2_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>